country_code_map = {
    "Australia": "en_au",
    "Macao China": "en_mo",
    "India": "en_in",
    "Japan": "ja_jp",
    "South Korea": "ko_kr",
    "Malaysia": "en_my",
    "New Zealand": "en_nz",
    "Singapore": "en_sg",
    "Hong Kong, China": "en_hk",
    "Brazil": "pt_br",
    "Chile": "es",
    "Colombia": "es_co",
    "Czech Republic": "cs_cz",
    "France": "fr_fr",
    "Germany": "de_de",
    "Italy": "it_it",
    "Portugal": "pt_pt",
    "Spain": "es_es",
    "Canada": "en_ca",
    "Mexico": "es_mx",
    "United States": "",
    "united Kingdom":"en_uk"
}